# Generated by Django 6.0.4 on 2026-05-04 10:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcelle', models.CharField(max_length=100, unique=True)),
                ('usage', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('proprietaire', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
